apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: gitlab-user-role
  namespace: pg
spec:
  cluster:
    name: pg-cluster
  name: gitlab
  comment: "Gitlab user role for Postgres"
  login: true
  superuser: false
  createdb: true
  passwordSecret:
    name: gitlab-infos
---
apiVersion: v1
stringData:
  username: gitlab
  password: eu_amo_a_42
kind: Secret
metadata:
  name: gitlab-infos
  namespace: pg
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
