apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: default
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:stonking-20260622
        command: ["/bin/sleep", "infinity"]
