Vagrant.configure("2") do |config|
  
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
  
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202510.26.0"

  config.vm.provision "shell", inline: "swapoff -a; sed -i '/\sswap\s/s/^/#/' /etc/fstab;"

  config.vm.define "vde-freiS" do |machine|
    machine.vm.hostname = "vde-freiS"
    machine.vm.network "private_network", ip: "192.168.56.110", hostname: true
   
    machine.vm.provider :virtualbox do |vb|
      vb.name = "vde-freiS"
    end

    machine.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=0644 K3S_TOKEN=424242 sh -s - --node-ip=192.168.56.110"
  end
end
