Vagrant.configure("2") do |config|
  
  config.vm.provider :virtualbox do |vb|
    vb.memory = 512
    vb.cpus = 1
  end
  
  config.vm.box = "bento/debian-13.1"
  config.vm.box_version = "202510.26.0"
  
  config.vm.define "almarcos" do |machine|
    machine.vm.hostname = "almarcosS"
    machine.vm.network "private_network", ip: "192.168.56.110", hostname: true
   
    machine.vm.provider :virtualbox do |vb|
      vb.name = "almarcosS"
    end

    machine.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | K3S_TOKEN=424242 sh -s - --node-ip=192.168.56.110"
  end

  config.vm.define "eddos-sa" do |machine|
    machine.vm.hostname = "eddos-saSW"
    machine.vm.network "private_network", ip: "192.168.56.111", hostname: true
    
    machine.vm.provider :virtualbox do |vb|
      vb.name = "eddos-saSW"
    end

    machine.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=424242 sh -s - --node-ip=192.168.56.111"
  end

end