Vagrant.configure("2") do |config|

  config.vm.define "almarcos" do |machine|
    machine.vm.box = "cloud-image/debian-13"
    machine.vm.box_version = "20260509.2473.0"
    
    config.vm.provider :virtualbox do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "almarcos"
    end
    
  end

end