nginx-ingress:
  enabled: false
certmanager:
  install: false
global:
  gatewayApi:
    configureCertmanager: false
    enabled: true
    installEnvoy: true
  certificates:
    selfSigned: true
  ingress:
    enabled: false
    provider: gateway
    configureCertmanager: false
  redis:
    host: valkey.default.svc.cluster.local
    auth:
      secret: valkey-auth
      key: default-password
  psql:
    host: gitlab-rails-db-rw.default.svc.cluster.local
    password:
      secret: gitlab-rails-db-app
      key: password
  ingress:
    configureCertmanager: false
  hosts:
    https: true
    domain: 10.0.2.15.nip.io
    externalIP: 10.0.2.15
  rails:
    bootsnap:
      enabled: false
  shell:
    port: 32022
  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-object-storage
        key: config
    artifacts:
      bucket: gitlab-artifacts
    lfs:
      bucket: git-lfs
    uploads:
      bucket: gitlab-uploads
    packages:
      bucket: gitlab-packages
    externalDiffs:
      enabled: true
      bucket: gitlab-mr-diffs
    terraformState:
      enabled: true
      bucket: gitlab-terraform-state
    ciSecureFiles:
      enabled: true
      bucket: gitlab-ci-secure-files
    agentPlanContent:
      enabled: true
      bucket: gitlab-agent-plan-content
    dependencyProxy:
      enabled: true
      bucket: gitlab-dependency-proxy
installCertmanager: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    service:
      type: NodePort
      nodePort: 32022
  toolbox:
    backups:
      objectStorage:
        config:
          secret: gitlab-object-storage-s3cmd
          key: config
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
  storage:
    secret: gitlab-registry-storage
    key: config
    redirect:
      disable: true

gatewayApiResources:
  gateway:
    addresses:
    - type: IPAddress
      value: "10.0.2.15"
    infrastructure:
      annotations: {}
